=== bryanli2018/wsn-device-drivers/tr.wsn-device-metadatenapps/metadatenservice/src/main/resources/sensors.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="de/uniluebeck/itm/metadatenservice/config" xmlns:tns="de/uniluebeck/itm/metadatenservice/config"
	elementFormDefault="qualified">
	<xsd:complexType name="capability">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string" minOccurs="1" maxOccurs="1"></xsd:element>
			<xsd:element name="datatype" type="xsd:string" minOccurs="1" maxOccurs="1"></xsd:element>
			<xsd:element name="unit" type="xsd:string" minOccurs="1" maxOccurs="1"></xsd:element>
			<xsd:element name="default" type="xsd:integer" minOccurs="1" maxOccurs="1"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="node">
		<xsd:sequence>
			<xsd:element name="nodeid" type="xsd:string" minOccurs="1" maxOccurs="1"></xsd:element>
			<xsd:element name="description" type="xsd:string"
				minOccurs="0" maxOccurs="1"></xsd:element>
			<xsd:element name="microcontroller" type="xsd:string"
				minOccurs="0" maxOccurs="1"></xsd:element>
			<xsd:element name="ipAddress" type="xsd:string"
				minOccurs="0" maxOccurs="1"></xsd:element>
			<xsd:element name="Port" type="xsd:integer" minOccurs="0"
				maxOccurs="1"></xsd:element>
			<xsd:element name="capability" type="tns:capability" minOccurs="0" maxOccurs="unbounded"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="nodeList">
		<xsd:sequence>
			<xsd:element name="node" type="tns:node" maxOccurs="unbounded"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:element name="nodeList" type="tns:nodeList"></xsd:element>
</xsd:schema>

=== bryanli2018/wsn-device-drivers/rsc.remote/rsc.remote.server/src/main/resources/sensors.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns0:nodeList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:ns0="de/uniluebeck/itm/metadatenservice/config"
	xsi:schemaLocation="de/uniluebeck/itm/metadatenservice/config sensors.xsd ">
	<ns0:node>
		<ns0:nodeid>3</ns0:nodeid>
		<ns0:description>wisebed</ns0:description>
		<ns0:microcontroller>TI MSP430</ns0:microcontroller>
		<ns0:ipAddress></ns0:ipAddress>
		<ns0:Port>1237</ns0:Port>
		<ns0:capability>
			<ns0:name>urn:wisebed:node:capability:temp</ns0:name>
			<ns0:datatype>integer</ns0:datatype>
			<ns0:unit>celsius</ns0:unit>
			<ns0:default>2</ns0:default>
		</ns0:capability>
		<ns0:capability>
			<ns0:name>urn:wisebed:node:capability:light</ns0:name>
			<ns0:datatype>integer</ns0:datatype>
			<ns0:unit>lux</ns0:unit>
			<ns0:default>2</ns0:default>
		</ns0:capability>
	</ns0:node>
	<ns0:node>
		<ns0:nodeid>4</ns0:nodeid>
		<ns0:description>wisebed</ns0:description>
		<ns0:microcontroller>TI MSP430</ns0:microcontroller>
		<ns0:ipAddress></ns0:ipAddress>
		<ns0:Port>1237</ns0:Port>
		<ns0:capability>
			<ns0:name>urn:wisebed:node:capability:temp</ns0:name>
			<ns0:datatype>integer</ns0:datatype>
			<ns0:unit>celsius</ns0:unit>
			<ns0:default>2</ns0:default>
		</ns0:capability>
		<ns0:capability>
			<ns0:name>urn:wisebed:node:capability:light</ns0:name>
			<ns0:datatype>integer</ns0:datatype>
			<ns0:unit>lux</ns0:unit>
			<ns0:default>2</ns0:default>
		</ns0:capability>
	</ns0:node>
</ns0:nodeList>
