=== bryanli2018/wsn-device-drivers/RPC-Prototype/src/main/resources/devices.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://xml.netbeans.org/schema/devices"
    xmlns:tns="http://xml.netbeans.org/schema/devices"
    elementFormDefault="qualified">
    <xsd:complexType name="Device">
        <xsd:sequence>
            <xsd:element name="KnotenTyp" type="xsd:string"></xsd:element>
            <xsd:element name="Port" type="xsd:int"></xsd:element>
            <xsd:element name="TestBed" type="xsd:string" minOccurs="0"></xsd:element>
            <xsd:element name="Sensors" type="tns:Sensors" minOccurs="0"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="Sensors">
        <xsd:sequence>
            <xsd:element name="Sensor" type="xsd:string" maxOccurs="unbounded" minOccurs="1"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="DeviceList">
        <xsd:sequence>
            <xsd:element name="newElement" type="tns:Device" maxOccurs="unbounded"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="DeviceList" type="tns:DeviceList"></xsd:element>
</xsd:schema>

=== bryanli2018/wsn-device-drivers/RPC-Prototype/src/main/resources/devices.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : devices.xml
    Created on : 2. Dezember 2010, 14:46
    Author     : Schuett
    Description:
        Purpose of the document follows.
-->

<ns0:DeviceList  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:ns0='http://xml.netbeans.org/schema/devices'
   xsi:schemaLocation='http://xml.netbeans.org/schema/devices/devices.xsd'>
    <ns0:newElement>
        <ns0:KnotenTyp>isense</ns0:KnotenTyp>
        <ns0:Port>1111</ns0:Port>
        <ns0:Sensors>
            <ns0:Sensor>temp</ns0:Sensor>
            <ns0:Sensor>hydro</ns0:Sensor>
        </ns0:Sensors>
    </ns0:newElement>
    <ns0:newElement>
        <ns0:KnotenTyp>jennec</ns0:KnotenTyp>
        <ns0:Port>2222</ns0:Port>
        <ns0:TestBed>ITM</ns0:TestBed>
        <ns0:Sensors>
            <ns0:Sensor>temp</ns0:Sensor>
        </ns0:Sensors>
    </ns0:newElement>
    <ns0:newElement>
        <ns0:KnotenTyp>pacemate</ns0:KnotenTyp>
        <ns0:Port>3333</ns0:Port>
        <ns0:TestBed>ITM</ns0:TestBed>
    </ns0:newElement>

</ns0:DeviceList>
