=== bryanli2018/wsn-device-drivers/rsc.remote/rsc.remote.server/src/main/resources/devices.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="de/uniluebeck/itm/tcp/JaxDevices"
    xmlns:tns="de/uniluebeck/itm/tcp/JaxDevices"
    elementFormDefault="qualified">
    <xsd:complexType name="jaxbDevice">
        <xsd:sequence>
        	<xsd:element name="DeviceId" type="xsd:string" minOccurs="1" maxOccurs="1">
        	       	<xsd:annotation>
						<xsd:documentation> The unique Id of Device</xsd:documentation>
					</xsd:annotation>
        	</xsd:element>
            <xsd:element name="DeviceType" type="xsd:string" minOccurs="1" maxOccurs="1">
        	       	<xsd:annotation>
						<xsd:documentation> The full-path Classname of the Device. Example: de.uniluebeck.itm.rsc.drivers.core.mockdevice.MockDevice</xsd:documentation>
					</xsd:annotation>
            </xsd:element>
            <xsd:element name="ConnectionType" type="xsd:string" minOccurs="1" maxOccurs="1">
            		<xsd:annotation>
						<xsd:documentation> The full-path Classname of the Connection for the Device. Example: de.uniluebeck.itm.rsc.drivers.core.mockdevice.MockConnection</xsd:documentation>
					</xsd:annotation>
            </xsd:element>
            <xsd:element name="Port" type="xsd:string" minOccurs="1" maxOccurs="1">
            		<xsd:annotation>
						<xsd:documentation> The physical OS-port of the Device.</xsd:documentation>
					</xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="jaxbDeviceList">
        <xsd:sequence>
            <xsd:element name="jaxbDevice" type="tns:jaxbDevice" maxOccurs="unbounded"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="jaxbDeviceList" type="tns:jaxbDeviceList">
    	<xsd:annotation>
			<xsd:documentation> A list with all devices</xsd:documentation>
		</xsd:annotation>
    </xsd:element>
</xsd:schema>

=== bryanli2018/wsn-device-drivers/rsc.remote/rsc.remote.server/src/main/resources/devices.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns0:jaxbDeviceList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xmlns:ns0="de/uniluebeck/itm/tcp/JaxDevices"
		xsi:schemaLocation="de/uniluebeck/itm/tcp/JaxDevices devices.xsd ">
 
 	<ns0:jaxbDevice>
 		<ns0:DeviceId>1</ns0:DeviceId>
        <ns0:DeviceType>de.uniluebeck.itm.rsc.drivers.core.mockdevice.MockDevice</ns0:DeviceType>
        <ns0:ConnectionType>de.uniluebeck.itm.rsc.drivers.core.mockdevice.MockConnection</ns0:ConnectionType>
        <ns0:Port>1111</ns0:Port>
    </ns0:jaxbDevice>
    <ns0:jaxbDevice>
 		<ns0:DeviceId>2</ns0:DeviceId>
        <ns0:DeviceType>de.uniluebeck.itm.rsc.drivers.core.mockdevice.MockDevice</ns0:DeviceType>
        <ns0:ConnectionType>de.uniluebeck.itm.rsc.drivers.core.mockdevice.MockConnection</ns0:ConnectionType>
        <ns0:Port>1112</ns0:Port>
    </ns0:jaxbDevice> <!-- 
    <ns0:jaxbDevice>
 		<ns0:DeviceId>3</ns0:DeviceId>
        <ns0:DeviceType>de.uniluebeck.itm.rsc.drivers.core.pacemate.PacemateDevice</ns0:DeviceType>
        <ns0:ConnectionType>de.uniluebeck.itm.rsc.drivers.core.generic.iSenseSerialPortConnection</ns0:ConnectionType>
        <ns0:Port>COM21</ns0:Port>
    </ns0:jaxbDevice>
     
     
     <ns0:jaxbDevice>
     	<ns0:DeviceId>4</ns0:DeviceId>
        <ns0:DeviceType>de.uniluebeck.itm.rsc.drivers.core.jennic.JennicDevice</ns0:DeviceType>
        <ns0:ConnectionType>de.uniluebeck.itm.rsc.drivers.core.generic.iSenseSerialPortConnection</ns0:ConnectionType>
        <ns0:Port>COM19</ns0:Port>
    </ns0:jaxbDevice>
    -->
</ns0:jaxbDeviceList>
