=== bryanli2018/wsn-device-drivers/tr.wsn-device-tcp-server/src/main/resources/devices.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="de/uniluebeck/itm/tcp/JaxDevices"
    xmlns:tns="de/uniluebeck/itm/tcp/JaxDevices"
    elementFormDefault="qualified">
    <xsd:complexType name="jaxbDevice">
        <xsd:sequence>
        	<xsd:element name="DeviceId" type="xsd:string" minOccurs="0"></xsd:element>
            <xsd:element name="DeviceName" type="xsd:string" minOccurs="0"></xsd:element>
            <xsd:element name="DeviceType" type="xsd:string" minOccurs="1" maxOccurs="1"></xsd:element>
            <xsd:element name="ConnectionType" type="xsd:string" minOccurs="1" maxOccurs="1"></xsd:element>
            <xsd:element name="Port" type="xsd:string" minOccurs="1" maxOccurs="1"></xsd:element>
            <xsd:element name="TestBed" type="xsd:string" minOccurs="0"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="jaxbDeviceList">
        <xsd:sequence>
            <xsd:element name="jaxbDevice" type="tns:jaxbDevice" maxOccurs="unbounded"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="jaxbDeviceList" type="tns:jaxbDeviceList"></xsd:element>
</xsd:schema>

=== bryanli2018/wsn-device-drivers/tr.wsn-device-tcp-server/src/main/resources/devices.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns0:jaxbDeviceList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xmlns:ns0="de/uniluebeck/itm/tcp/JaxDevices"
		xsi:schemaLocation="de/uniluebeck/itm/tcp/JaxDevices devices.xsd ">
 
 	<ns0:jaxbDevice>
 		<ns0:DeviceId>1</ns0:DeviceId>
        <ns0:DeviceName>mokDevice</ns0:DeviceName>
        <ns0:DeviceType>de.uniluebeck.itm.devicedriver.mockdevice.MockDevice</ns0:DeviceType>
        <ns0:ConnectionType>de.uniluebeck.itm.devicedriver.mockdevice.MockConnection</ns0:ConnectionType>
        <ns0:Port>1111</ns0:Port>
    </ns0:jaxbDevice>
    <ns0:jaxbDevice>
 		<ns0:DeviceId>2</ns0:DeviceId>
        <ns0:DeviceName>mokDevice</ns0:DeviceName>
        <ns0:DeviceType>de.uniluebeck.itm.devicedriver.mockdevice.MockDevice</ns0:DeviceType>
        <ns0:ConnectionType>de.uniluebeck.itm.devicedriver.mockdevice.MockConnection</ns0:ConnectionType>
        <ns0:Port>1112</ns0:Port>
    </ns0:jaxbDevice> <!-- 
    <ns0:jaxbDevice>
 		<ns0:DeviceId>3</ns0:DeviceId>
        <ns0:DeviceName>pacemateDevice</ns0:DeviceName>
        <ns0:DeviceType>de.uniluebeck.itm.devicedriver.pacemate.PacemateDevice</ns0:DeviceType>
        <ns0:ConnectionType>de.uniluebeck.itm.devicedriver.generic.iSenseSerialPortConnection</ns0:ConnectionType>
        <ns0:Port>COM21</ns0:Port>
    </ns0:jaxbDevice>
     
     
     <ns0:jaxbDevice>
        <ns0:DeviceName>JenicDevice</ns0:DeviceName>
        <ns0:DeviceType>de.uniluebeck.itm.devicedriver.jennic.JennicDevice</ns0:DeviceType>
        <ns0:ConnectionType>de.uniluebeck.itm.devicedriver.generic.iSenseSerialPortConnection</ns0:ConnectionType>
        <ns0:Port>COM19</ns0:Port>
    </ns0:jaxbDevice>
   
    <ns0:jaxbDevice>
        <ns0:DeviceName>jennic</ns0:DeviceName>
        <ns0:DeviceType>de.uniluebeck.itm.devicedriver.jennic.JennicDevice</ns0:DeviceType>
        <ns0:ConnectionType>de.uniluebeck.itm.devicedriver.generic.iSenseSerialPortConnection</ns0:ConnectionType>
        <ns0:Port>2222</ns0:Port>
        <ns0:TestBed>ITM</ns0:TestBed>
        <ns0:Sensors>
            <ns0:Sensor>temp</ns0:Sensor>
        </ns0:Sensors>
    </ns0:jaxbDevice>
    <ns0:jaxbDevice>
        <ns0:DeviceName>pacemate</ns0:DeviceName>
        <ns0:DeviceType>de.uniluebeck.itm.devicedriver.pacemate.PacemateDevice</ns0:DeviceType>
        <ns0:ConnectionType>de.uniluebeck.itm.devicedriver.generic.iSenseSerialPortConnection</ns0:ConnectionType>
        <ns0:Port>3333</ns0:Port>
        <ns0:TestBed>ITM</ns0:TestBed>
    </ns0:jaxbDevice>
    -->
</ns0:jaxbDeviceList>
